config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources :welcome, only: [:index]

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :recipes

  namespace :admin do
    resources :users
    resources :ingredients, only: [:new, :create, :edit, :update, :destroy, :index]
    resources :measurements, only: [:new, :create, :edit, :update, :destroy, :index]
  end
  
end

app/models/measurement.rb
class Measurement < ActiveRecord::Base

  #has_many :recipe_components

  validates :long_name, presence: true
  validates :short_name, presence: true, uniqueness: true

end

app/controllers/admin/measurements_controller.rb
class Admin::MeasurementsController < ApplicationController

  def index
    @measurements = Measurement.all
  end

  def new
    @measurement = Measurement.new
  end

  def create
    @measurement = Measurement.new(secure_params)

    if @measurement.save
      redirect_to admin_measurements_path, notice: "Added #{@measurement.long_name}"
    else
      render :new
    end
  end

  def edit
    @measurement = Measurement.find(params[:id])
  end

  def update
    @measurement = Measurement.find(params[:id])
    @measurement.update(secure_params)

    if @measurement.save
      redirect_to admin_measurements_path, notice: "Updated #{@measurement.long_name}"
    else
      render :edit
    end
  end

  def destroy
    @measurement = Measurement.find(params[:id])

    if @measurement.destroy
      redirect_to admin_measurements_path, notice: "Deleted #{@measurement.long_name}"
    else
      render :index
    end
  end

  protected

  def secure_params
    params.require(:measurement).permit(:long_name, :short_name)
  end

end

app/helpers/measurements_helper.rb
module MeasurementsHelper
end

app/views/admin/measurements/_form.html.erb
<%= link_to 'Back', admin_measurements_path %>
<%= form_for [:admin, @measurement] do |f| %>
    <% if @measurement.errors.any? %>
        <div>
          <%= pluralize(@measurement.errors.count, 'error') %>
          <ul>
            <% @measurement.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div>
      <%= f.label 'Name' %>
      <%= f.text_field 'long_name' %>
    </div>
    <div>
      <%= f.label 'Abbreviation' %>
      <%= f.text_field 'short_name', class: 'form-control', placeholder: 'e.g. Tbsp' %>
    </div>
    <div>
      <%= f.submit 'Submit' %>
    </div>
<% end %>

app/views/admin/measurements/edit.html.erb
<% if current_user.admin %>
    <h1>Admin/Measurements/Edit</h1>
    <%= render 'form' %>
<% else %>
    <h1>No Access</h1>
<% end %>

app/views/admin/measurements/index.html.erb
<% if current_user.admin %>

    <h1>Admin/Measurements/Index</h1>
    <% if @measurement && @measurement.errors.any? %>
        <div>
          <%= pluralize(@measurement.errors.count, 'error') %>
          <ul>
            <% @measurement.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= link_to 'Home', root_path %>
    <%= link_to 'Add another measurement', new_admin_measurement_path %>
    <table border="1">
      <% count = 1 %>
      <% @measurements.each do |measurement| %>
        <tr>
          <td><%= count %></td>
          <td><%= measurement.long_name %></td>
          <td><%= measurement.short_name %></td>
          <td><%= link_to 'edit', edit_admin_measurement_path(measurement) %></td>
          <td><%= link_to 'delete', admin_measurement_path(measurement), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
          <% count+= 1 %>
      <% end %>
    </table>

<% else %>
    <h1>No Access</h1>

<% end %>

app/views/admin/measurements/new.html.erb
<% if current_user.admin %>
    <h1>Admin/Measurements/New</h1>
    <%= render 'form' %>
<% else %>
    <h1>No Access</h1>
<% end %>