config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources :welcome, only: [:index]

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :recipes

  namespace :admin do
    resources :users
    resources :ingredients, only: [:new, :create, :edit, :update, :destroy, :index]
    resources :measurements, only: [:new, :create, :edit, :update, :destroy, :index]
  end
  
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  belongs_to :user
  has_many :stages, dependent: :destroy
  has_many :recipe_components, dependent: :destroy
  has_many :ingredients, :through => :stages
  has_many :measurements, :through => :stages

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  skip_before_action :verify_authenticity_token

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    @ingredients = Ingredient.all
    @measurements = Measurement.all
  end

  def create
    create_recipe_from_json(params)
    create_stage_from_json(params)
    @recipe = Recipe.last
    render json: @recipe, notice: "#{@recipe.name} added!"
  end

  def destroy
    @recipe = Recipe.find(params[:id])

    if @recipe.destroy
      redirect_to recipes_path, notice: "#{@recipe.name} deleted!"
    else
      render :index
    end
  end

end

app/helpers/recipes_helper.rb
module RecipesHelper

  def get_name(id)
    User.find(id).username
  end

end

app/views/recipes/index.html.erb
<h1>Recipes/Index</h1>
<% if @recipe && @recipe.errors.any? %>
    <div>
      <%= pluralize(@recipe.errors.count, 'error') %>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<%= link_to 'Home', root_path%>
<%= link_to 'Add Recipe', new_recipe_path %>
<table>
  <tr><th>Recipe</th><th>by</th></tr>
  <% @recipes.each do |recipe| %>
    <tr>
      <td><%= recipe.name %></td>
      <td><%= get_name(recipe.user_id) %></td>
      <td><%= link_to 'delete', recipe_path(recipe), method: :delete, data: {confirm: 'Are you sure?'} if current_user && current_user.id == recipe.user_id%></td>
    </tr>
  <% end %>
</table>

app/views/recipes/new.html.erb
<h1>Recipes/New</h1>

<%= link_to 'Back', recipes_path %>
<% if @recipe.errors.any? %>
    <div>
      <%= pluralize(@recipe.errors.count, 'error') %> prevented the recipe from being created:
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<form id="newRecipe">
  Recipe Name<input type="text" class="validate" id="recipe_name" name="recipe_name"><br>
  <div id="sandbox"></div>
  <div id="selectHolder"></div>
  <input type="submit" value="submit">
</form>

<button id="addStage">Add a Stage</button>

<script>

  $(function(){

      var ingredients = <%= raw @ingredients.to_json %>
      var measurements = <%= raw @measurements.to_json %>
      var stageCount = 1;
      var count = 1;

      $body = $("body");

      $(document).on({
          ajaxStart: function() { $body.addClass("loading");    },
          ajaxStop: function() { $body.removeClass("loading"); }
      });

      $("#addStage").on("click", function(){
          $("#sandbox").append("<br><div id='stage" + stageCount + "' data-count='1' style='border: 1px solid black; width: 400px;'>Instructions" +
                  "<textarea class='validate' name ='stage" + stageCount + "' style='height: 100px; width: 200px'></textarea><br>" +
                  "<button type='button' class='dynamicIngredients'>Add more ingredients</button><br></div>"); //add instructions field
          stageCount++;

      });

      //

      //[{name: "hello", id: 10}, {name: }]
      //get active record object and convert to json
      //create new functions to loop through and populate the fields
      //also can create for the edit page a form_for to populate the fields and use jquery for adding dynamic buttons


      $("#sandbox").on("click", "button.dynamicIngredients", function(){
          var origin = $(this).parent();
          addIngredients(origin);
          var dataCount = origin.data("count");
          dataCount++;
          origin.data("count", dataCount);

      });


      function addIngredients(origin){
          var id = origin.attr('id');
          var dataCount = origin.data("count");
          $(origin).append("<select class='validate' id='" + id + "_ingredients" + dataCount + "' name='" + id + "_" + dataCount + "_ingredients'></select>"); //add ingredients select
          $.each(ingredients, function(i, ingredient){ //options points looks for select id
              $("#" + id + "_ingredients" + dataCount + "").append("<option value='" + ingredient.id + "'>" + ingredient.name + "</option>");
          });
          $("#" + id + "_ingredients" + dataCount + "").prepend("<option value='' selected='selected'>select one</option>");

          $(origin).append("<input type='number' class='validate' name='" + id + "_" + dataCount + "_quantity'>");

          $(origin).append("<select class='validate' id='" + id + "_measurements" + dataCount + "' name='" + id + "_" + dataCount + "_measurements'></select><br>"); //add measurements select
          $.each(measurements, function(i, measurement){
              $("#" + id + "_measurements" + dataCount + "").append("<option value='" + measurement.id + "'>" + measurement.short_name + "</option>");
          });
          $("#" + id + "_measurements" + dataCount + "").prepend("<option value='' selected='selected'>select one</option>");

          count++;
      }

      $("#newRecipe").submit(function(event){
          event.preventDefault();
          if (validateForm()) {

              $('input:submit').attr("disabled", true);
              var formData = $("#newRecipe").serializeArray();

              $.ajax({
                  type  : 'POST',
                  url   : '<%= recipes_path %>',
                  data  : formData
              })
              .done(function(data){
                console.log('looking good!');
                console.log(data);
                window.location = '<%= recipes_path %>';
              })
              .error(function(data){
                console.log('something went wrong!');
                console.log(data);
              });

          } else {
              window.alert("All Fields required!");
          }

      });

      function validateForm() {
          var isValid = true;
          $('.validate').each(function() {
              if ( $(this).val() === '' )
                  isValid = false;
          });
          return isValid;
      }


      console.log('ready!');
  });

</script>