config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources :welcome, only: [:index]

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :recipes

  namespace :admin do
    resources :users
    resources :ingredients, only: [:new, :create, :edit, :update, :destroy, :index]
    resources :measurements, only: [:new, :create, :edit, :update, :destroy, :index]
  end
  
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base

  #has_many :recipe_components

  validates :name, presence: true
  validates :name, uniqueness: true

end

app/controllers/admin/ingredients_controller.rb
class Admin::IngredientsController < ApplicationController

  def index
    @ingredients = Ingredient.all
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(secure_params)

    if @ingredient.save
      redirect_to admin_ingredients_path, notice: "Added #{@ingredient.name}"
    else
      render :new
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def show

  end

  def update
    @ingredient = Ingredient.find(params[:id])
    @ingredient.update(secure_params)

    if @ingredient.save
      redirect_to admin_ingredients_path, notice: 'updated'
    else
      render :edit
    end

  end

  def destroy
    @ingredient = Ingredient.find(params[:id])

    if @ingredient.destroy
      redirect_to admin_ingredients_path, notice: "#{@ingredient.name} deleted! "
    else
      redirect_to admin_ingredients_path, notice: "failed to delete #{@ingredients.name}"
    end

  end

  protected

  def secure_params
    params.require(:ingredient).permit(:name)
  end

end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/admin/ingredients/_form.html.erb
<%= link_to 'Back', admin_ingredients_path %>
<%= form_for [:admin, @ingredient] do |f| %>
    <% if @ingredient.errors.any? %>
        <div>
          <%= pluralize(@ingredient.errors.count, 'error') %> prevented the ingredient from being created:
          <ul>
            <% @ingredient.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div>
      <%= f.label 'name' %><br>
      <%= f.text_field 'name' %>
    </div>
    <div><%= f.submit 'Submit' %></div>
<% end %>

app/views/admin/ingredients/edit.html.erb
<% if current_user.admin? %>

    <h1>admin/ingredient/edit</h1>

    <%= form_for [:admin, @ingredient] do |f| %>
        <% if @ingredient.errors.any? %>
            <div>
              <%= pluralize(@ingredient.errors.count, 'error') %> prevented the account from being created:
              <ul>
                <% @ingredient.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <div>
          <%= f.label 'name' %><br>
          <%= f.text_field 'name' %>
        </div>
        <div><%= f.submit 'Submit' %></div>
    <% end %>

<% else %>
    <h1>No Access</h1>

<% end %>

app/views/admin/ingredients/index.html.erb
<% if current_user.admin %>

    <h1>Admin/Ingredients/Index</h1>

    <%= link_to 'home', root_path %>
    <%= link_to 'add another ingredient', new_admin_ingredient_path %>
    <table border="1">
      <% count = 1 %>
      <% @ingredients.each do |ingredient| %>
        <tr>
          <td><%= count %></td>
          <td><%= ingredient.name %></td>
          <td><%= link_to 'edit', edit_admin_ingredient_path(ingredient) %></td>
          <td><%= link_to 'delete', admin_ingredient_path(ingredient), method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
        <% count += 1 %>
      <% end %>
    </table>

<% else %>
    <h1>No Access</h1>

<% end %>

app/views/admin/ingredients/new.html.erb
<% if current_user.admin? %>

    <h1>Admin/Ingredients/New</h1>
    <%= render 'form' %>

<% else %>
    <h1>No Access</h1>

<% end %>