config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  resources :welcome, only: [:index]

  resources :sessions, only: [:new, :create, :destroy]

  resources :users, only: [:new, :create, :edit, :update, :show]
  resources :recipes

  namespace :admin do
    resources :users
    resources :ingredients, only: [:new, :create, :edit, :update, :destroy, :index]
    resources :measurements, only: [:new, :create, :edit, :update, :destroy, :index]
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :recipes

  validates :username, :email, uniqueness: true
  validates :username, :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(secure_params)

    if @user.save
      redirect_to admin_users_path, notice: "User, #{@user.first_name} created!"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(secure_params)

    if @user.save
      redirect_to admin_users_path, notice: 'updated!'
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])

    if @user.destroy
      redirect_to admin_users_path, notice: "#{@user.username} deleted! "
    else
      redirect_to admin_users_path, notice: "failed to delete #{@user.username}"
    end
  end


    protected

  def secure_params
    params.require(:user).permit(:username, :email, :first_name, :last_name, :password, :password_confirmation, :admin)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(secure_params)

    if @user.save
      if current_user.admin
        redirect_to admin_users_path, notice: "User, #{@user.first_name} created!"
      else
        session[:user_id] = @user.id
        redirect_to recipes_path, notice: "Happy eating, #{@user.first_name}!"
      end
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(secure_params)

    if @user.save
      if current_user.admin
        redirect_to admin_users_path(params[:id]), notice: 'updated!'
      else
        redirect_to user_path(params[:id]), notice: 'updated!'
      end

    else
      render :edit
    end
  end

  protected

  def secure_params
    params.require(:user).permit(:username, :email, :first_name, :last_name, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def is_admin
    if current_user
      if current_user.admin
        true
      else
        false
      end
    else
      false
    end
  end

end

app/views/admin/users/edit.html.erb
<% if current_user.admin? %>
    <h1>admin/users/:id/edit</h1>
    <%= form_for [:admin, @user] do |f| %>
        <%= render partial: 'users/edit', locals: {f: f, user: @user} %>
        <div><%= f.submit 'Submit' %></div>
    <% end %>
<% else %>
    <h1>No Access</h1>
<% end %>

app/views/admin/users/index.html.erb
<% if current_user.admin? %>
    <%= link_to 'home', root_path %>
    <%= link_to 'add new user', new_admin_user_path %>
    <table border="1">
        <% @users.each do |user| %>
            <tr>
              <td><%= user.username %></td>
              <td><%= user.full_name %></td>
              <td><%= link_to 'edit', edit_admin_user_path(user.id) %></td>
              <td><%= link_to 'delete', admin_user_path(user.id), method: :delete, data: {confirm: 'Are you sure?'}%></td>
            </tr>
        <% end %>
    </table>
<% else %>
    <h1>No Access</h1>
<% end %>

app/views/admin/users/new.html.erb
<% if current_user.admin? %>
    <%= form_for [:admin, @user] do |f| %>
        <%= render partial: 'users/new', locals: {f: f, user: @user} %>
        <div><%= f.submit 'Submit' %></div>
    <% end %>
<% else %>
    <h1>No Access</h1>
<% end %>